### ISSUE TITLE
Error when clicking on Bake car Steering and Rotation (with Blender 4.1 add-on fix)

### ISSUE THREAD

**Issue by Luke9831** [digicreatures/rigacar#137]
![Screenshot 2024-07-23 1433352](https://github.com/user-attachments/assets/13d90b80-2e3f-4f5b-81b1-d739cab03d0c)

**Comment by arielsonico** [comment]
Same thing ocurred to me!

**Comment by lavibeats** [comment]
same + pose mode does not work for me

**Comment by batonchick1** [comment]
@jiapeiLu  Hi! Is it possible for you to help with this error? Thanks!

**Comment by batonchick1** [comment]
corrected in #133

**Comment by Luke9831** [comment]
> corrected in #133

I still get the error when using the 4.1 fixed version of Ricgacar
